/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.infrastructure.util.StringUtil;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author raiii
 */
public class CursoEditar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoEditar.class.getName());

    /**
     * Creates new form CursoEditar
     */
    private CursoIController cursoIController;
    private final Curso curso;
    private final CursoListar telaListar;
    public CursoEditar(Curso curso, CursoListar telaListar, CursoIController cursoIController){
        this.telaListar = telaListar;
        this.curso = curso;
        this.cursoIController = cursoIController;

        initComponents();
        
        txtNovoNome.setText(curso.getNome());
        txtNovoCodigo.setText(curso.getCodigoCurso());
        txtNovaCarga.setText(String.valueOf(curso.getCargaHoraria()));

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNovoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNovoCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNovaCarga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        checkAtivo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Novo nome: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 60, -1, -1));

        txtNovoNome.setText("Digite aqui");
        getContentPane().add(txtNovoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 57, 118, -1));

        jLabel2.setText("Novo código:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 100, -1, -1));

        txtNovoCodigo.setText("Digite aqui");
        getContentPane().add(txtNovoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 97, 118, -1));

        jLabel3.setText("Nova carga horária: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 140, -1, -1));

        txtNovaCarga.setText("Digite aqui");
        getContentPane().add(txtNovaCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 137, 102, -1));

        jButton1.setText("Salvar Mudanças");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 210, -1, -1));

        checkAtivo.setText("Ativo");
        checkAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAtivoActionPerformed(evt);
            }
        });
        getContentPane().add(checkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 178, 85, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        curso.setNome(txtNovoNome.getText());
        curso.setCodigoCurso(txtNovoCodigo.getText());
        curso.setCargaHoraria(txtNovaCarga.getText());
        
        if (StringUtil.isEmpty(curso.getNome()) || 
                StringUtil.isEmpty(curso.getCodigoCurso()) ||
                StringUtil.isEmpty(curso.getCargaHoraria())){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            return;
        }
        
        try{
            cursoIController.update(curso);
            JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
            
            telaListar.atualizarTabela();
            this.dispose();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERRO ao atualizar dados!" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAtivoActionPerformed
        curso.setAtivo(checkAtivo.isSelected());
    }//GEN-LAST:event_checkAtivoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkAtivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNovaCarga;
    private javax.swing.JTextField txtNovoCodigo;
    private javax.swing.JTextField txtNovoNome;
    // End of variables declaration//GEN-END:variables
}
